# .github/labeler.yml

# List of labels and corresponding minimatch globs
App: Apps/*
bug:
  globs:
    - '*bug*'
    - '*error*'
labels:
  - label: feature
    globs:
      - '*feature*'
      - '*enhancement*'

# End of configuration
