name: Update Recent Commits

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  update-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install requests

      - name: Update recent_commits.txt
        run: |
          python recent_commits.txt > temp.txt
          mv temp.txt recent_commits.txt
          git config --global user.name "HydraIndustries"
          git config --global user.email "kahlob@hydratechnologies.us"
          git commit -am "Update recent commits" --allow-empty
          git push
